apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak-mcp

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: keycloak-mcp-server
  app.kubernetes.io/managed-by: kustomize

images:
  - name: quay.io/sshaaf/keycloak-mcp-server
    newTag: latest

