apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak-mcp-server
  labels:
    app: keycloak-mcp-server
    app.kubernetes.io/name: keycloak-mcp-server
spec:
  to:
    kind: Service
    name: keycloak-mcp-server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

